---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: romver-resource

run:
  path: sh
  dir: romver-resource
  args:
  - -c
  - |
    go test -v ./...
