name: CI
on:
  push:
    branches:
    - master
    tags-ignore:
    - "*.*.*"
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17"]
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@master
    - name: go test
      run: |
        go test -v ./...
      env:
        ROMVER_TESTING_GITHUB_URI: https://github.com/cappyzawa/romver-resource
        ROMVER_TESTING_GITHUB_BRANCH: integration
        ROMVER_TESTING_GITHUB_USERNAME: github-actions
        ROMVER_TESTING_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        ROMVER_TESTING_GITHUB_PRIVATE_KEY: ${{ secrets.ROMVER_TESTING_GITHUB_PRIVATE_KEY }}
