name: CI
on:
  push:
    branches:
    - master
    tags-ignore:
    - "*.*.*"
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17"]
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@master
    - name: install ginkgo
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
    - name: ginkgo
      run: |
        ginkgo -r -v -skip="RomverResource"
