name: Release
on:
  push:
    tags:
    - "v*.*.*"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
  publish-image-to-dockerhub:
    name: Publish Image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cappyzawa/romver-resource
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        buildargs: ROMVER_TESTING_GITHUB_URI,ROMVER_TESTING_GITHUB_BRANCH,ROMVER_TESTING_GITHUB_USERNAME,ROMVER_TESTING_GITHUB_PASSWORD
      env:
        ROMVER_TESTING_GITHUB_URI: https://github.com/cappyzawa/romver-resource
        ROMVER_TESTING_GITHUB_BRANCH: integration
        ROMVER_TESTING_GITHUB_USERNAME: github-actions
        ROMVER_TESTING_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  publish-image-to-github:
    name: Publish Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: IMAGE_ID docker.pkg.github.com/cappyzawa/romver-resource/resource
        username: github-actions
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_names: true
        buildargs: ROMVER_TESTING_GITHUB_URI,ROMVER_TESTING_GITHUB_BRANCH,ROMVER_TESTING_GITHUB_USERNAME,ROMVER_TESTING_GITHUB_PASSWORD
      env:
        ROMVER_TESTING_GITHUB_URI: https://github.com/cappyzawa/romver-resource
        ROMVER_TESTING_GITHUB_BRANCH: integration
        ROMVER_TESTING_GITHUB_USERNAME: github-actions
        ROMVER_TESTING_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
